Declare SIG1T as an array in gcycle.F90
Fixes Intel LLVM compiler (ifx) error:

physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(237): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
      CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
-----------^